//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csvFileReader.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public int ContactDetailId { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int ContactSummaryId { get; set; }
    
        public virtual ContactSummary ContactSummary { get; set; }
    }
}
